rm(list=ls())

#Set path to the working directory containing:
#1. INTERMAGNET data set - to be taken from the INTERMAGNET web-site, and reformatted 
#accordingly - #reformatted original data enclosed
#2. TEC data set, as derived from the RINEX GPS observations using 
# GPS TEC software - enclosed

library(tidyverse)
getCurrentFileLocation <-  function()
{
    this_file <- commandArgs() %>% 
    tibble::enframe(name = NULL) %>%
    tidyr::separate(col=value, into=c("key", "value"), sep="=", fill='right') %>%
    dplyr::filter(key == "--file") %>%
    dplyr::pull(value)
    if (length(this_file)==0)
    {
      this_file <- rstudioapi::getSourceEditorContext()$path
    }
    return(dirname(this_file))
}

setwd(getCurrentFileLocation())

#Declaration of the R libraries utilised

library(data.table)
library(DataExplorer)
library(corrplot)
library(lubridate)
library(fitdistrplus)
library(weird)

oldw <- getOption("warn")
options(warn = -1)

# Reading the annual observed TEC data at Darwin, NT in 2014 and
# data frame arrangement

iono <- matrix(nrow=0, ncol = 3)
data <- as.data.frame(read.csv('darwin2014.csv', header=TRUE, 
                               sep =',', skip=0))

data <- data[,-1]
summary(data)
pe <- data[data$min==0 & data$sec==0,]

# Reading the annual estimated Dst and ap data in 2014 and
# data frame arrangement

geo <- as.data.frame(read.csv('Dstap2014.dat',header=FALSE,sep=''))
colnames(geo) <- c('year','DOY','hr','Dst','ap')
summary(geo)

# Merging TEC and Dst&ap data frames
dataset <- merge(pe, geo, by = c('DOY', 'hr'))
dataset <- dataset[,-c(3,4,10)]
summary(dataset)

dataset2 <- dataset[,-c(1,2)]

# Data set reduction by expelling TEC>=300 outliers
iono3 <- dataset2[dataset2$TEC<300,]

#iono3 <- iono3[c(1:8000),]

# Exloratory analysis of observations per variables
plot_histogram(dataset2, title = 'TEC<300')
dev.copy(pdf, "dataset2histogram.pdf")
dev.off()
plot_histogram(iono3, title = 'TEC<300')
dev.copy(pdf, "iono3histogram.pdf")
dev.off()
#Correlation
plot_correlation(dataset2, maxcat = 5L)
dev.copy(pdf, "dataset2correlation.pdf")
dev.off()
plot_correlation(iono3, maxcat = 5L)
dev.copy(pdf, "iono3correlation.pdf")
dev.off()
#Box-plots per Dst values, source of the classification criteria
plot_boxplot(dataset2, by = "Dst")
dev.copy(pdf, "dataset2boxplot.pdf")
dev.off()
plot_boxplot(iono3, by = "Dst")
dev.copy(pdf, "iono3boxplot.pdf")
dev.off()
#Scatterplots per Dst values, source of the classification criteria
plot_scatterplot(dataset2, by = 'TEC', sampled_rows = 1000L)
dev.copy(pdf, "dataset2scatterplot.pdf")
dev.off()
plot_scatterplot(iono3, by = 'Dst', sampled_rows = 1000L)
dev.copy(pdf, "iono3scatterplot.pdf")
dev.off()

### Dst-based classification under the following rule:
# 15 ... 50 positive phase of the storm -> P
# -20 ... 15 normal -> N
# -55 ... -20 recovery phase (mostly) -> R
# -85 ... -55 through -> T
# -120 ... -85 extreme -> E

Dst_class <- character()
P <- iono3[iono3$Dst >= 15,]
N <- iono3[(iono3$Dst < 15 & iono3$Dst >= -20),]
R <- iono3[(iono3$Dst < (-20) & iono3$Dst >= (-55)),]
T <- iono3[(iono3$Dst < (-55) & iono3$Dst >= (-85)),]
E <- iono3[(iono3$Dst < -85),]

sink("data_vars_2.txt")
print(summary(dataset2))
sink()

sink("data_vars_3.txt")
print(summary(iono3))
sink()

sink("data_vars_3_P.txt")
print(summary(P))
sink()
sink("data_vars_3_N.txt")
print(summary(N))
sink()
sink("data_vars_3_R.txt")
print(summary(R))
sink()
sink("data_vars_3_T.txt")
print(summary(T))
sink()
sink("data_vars_3_E.txt")
print(summary(E))
sink()

getQQ <- function(qqdata, sth)
{
  qqnorm(qqdata, pch = 1, frame = FALSE, main = paste("Normal Q-Q Plot", sth, sep = "\n"), ylab = paste("Sample Quantiles", sth),)
  qqline(qqdata, col = "steelblue", lwd = 2)
}

sink("data_vars_2_test_normal.txt")
print(length(dataset2$TEC))
getQQ(dataset2$TEC, "TEC")
dev.copy(pdf, "data_vars_2_TEC_qqplot.pdf")
dev.off()
getQQ(dataset2$dTEC, "dTEC")
dev.copy(pdf, "data_vars_2_dTEC_qqplot.pdf")
dev.off()
getQQ(dataset2$Bx, "Bx")
dev.copy(pdf, "data_vars_2_Bx_qqplot.pdf")
dev.off()
getQQ(dataset2$By, "By")
dev.copy(pdf, "data_vars_2_By_qqplot.pdf")
dev.off()
getQQ(dataset2$Bz, "Bz")
dev.copy(pdf, "data_vars_2_Bz_qqplot.pdf")
dev.off()
getQQ(dataset2$Dst, "Dst")
dev.copy(pdf, "data_vars_2_Dst_qqplot.pdf")
dev.off()
getQQ(dataset2$ap, "ap")
dev.copy(pdf, "data_vars_2_ap_qqplot.pdf")
dev.off()
#print(shapiro.test(dataset2$TEC))
#print(shapiro.test(dataset2$dTEC))
#print(shapiro.test(dataset2$Bx))
#print(shapiro.test(dataset2$By))
#print(shapiro.test(dataset2$Bz))
#print(shapiro.test(dataset2$Dst))
#print(shapiro.test(dataset2$ap))
print(ks.test(dataset2$TEC, "pnorm"))
print(ks.test(dataset2$dTEC, "pnorm"))
print(ks.test(dataset2$Bx, "pnorm"))
print(ks.test(dataset2$By, "pnorm"))
print(ks.test(dataset2$Bz, "pnorm"))
print(ks.test(dataset2$Dst, "pnorm"))
print(ks.test(dataset2$ap, "pnorm"))
sink()

sink("data_vars_3_test_normal.txt")
print(length(iono3$TEC))
getQQ(iono3$TEC, "TEC<300 TEC")
dev.copy(pdf, "data_vars_3_TEC_qqplot.pdf")
dev.off()
getQQ(iono3$dTEC, "TEC<300 dTEC")
dev.copy(pdf, "data_vars_3_dTEC_qqplot.pdf")
dev.off()
getQQ(iono3$Bx, "TEC<300 Bx")
dev.copy(pdf, "data_vars_3_Bx_qqplot.pdf")
dev.off()
getQQ(iono3$By, "TEC<300 By")
dev.copy(pdf, "data_vars_3_By_qqplot.pdf")
dev.off()
getQQ(iono3$Bz, "TEC<300 Bz")
dev.copy(pdf, "data_vars_3_Bz_qqplot.pdf")
dev.off()
getQQ(iono3$Dst, "TEC<300 Dst")
dev.copy(pdf, "data_vars_3_Dst_qqplot.pdf")
dev.off()
getQQ(iono3$ap, "TEC<300 ap")
dev.copy(pdf, "data_vars_3_ap_qqplot.pdf")
dev.off()
#print(shapiro.test(iono3$TEC))
#print(shapiro.test(iono3$dTEC))
#print(shapiro.test(iono3$Bx))
#print(shapiro.test(iono3$By))
#print(shapiro.test(iono3$Bz))
#print(shapiro.test(iono3$Dst))
#print(shapiro.test(iono3$ap))
print(ks.test(iono3$TEC, "pnorm"))
print(ks.test(iono3$dTEC, "pnorm"))
print(ks.test(iono3$Bx, "pnorm"))
print(ks.test(iono3$By, "pnorm"))
print(ks.test(iono3$Bz, "pnorm"))
print(ks.test(iono3$Dst, "pnorm"))
print(ks.test(iono3$ap, "pnorm"))
sink()

sink("data_vars_3_P_test_normal.txt")
print(length(P$TEC))
getQQ(P$TEC, "P TEC")
dev.copy(pdf, "data_vars_3_P_TEC_qqplot.pdf")
dev.off()
getQQ(P$dTEC, "P dTEC")
dev.copy(pdf, "data_vars_3_P_dTEC_qqplot.pdf")
dev.off()
getQQ(P$Bx, "P Bx")
dev.copy(pdf, "data_vars_3_P_Bx_qqplot.pdf")
dev.off()
getQQ(P$By, "P By")
dev.copy(pdf, "data_vars_3_P_By_qqplot.pdf")
dev.off()
getQQ(P$Bz, "P Bz")
dev.copy(pdf, "data_vars_3_P_Bz_qqplot.pdf")
dev.off()
getQQ(P$Dst, "P Dst")
dev.copy(pdf, "data_vars_3_P_Dst_qqplot.pdf")
dev.off()
getQQ(P$ap, "P ap")
dev.copy(pdf, "data_vars_3_P_ap_qqplot.pdf")
dev.off()
print(shapiro.test(P$TEC))
print(shapiro.test(P$dTEC))
print(shapiro.test(P$Bx))
print(shapiro.test(P$By))
print(shapiro.test(P$Bz))
print(shapiro.test(P$Dst))
print(shapiro.test(P$ap))
print(ks.test(P$TEC, "pnorm"))
print(ks.test(P$dTEC, "pnorm"))
print(ks.test(P$Bx, "pnorm"))
print(ks.test(P$By, "pnorm"))
print(ks.test(P$Bz, "pnorm"))
print(ks.test(P$Dst, "pnorm"))
print(ks.test(P$ap, "pnorm"))
sink()

sink("data_vars_3_N_test_normal.txt")
print(length(N$TEC))
getQQ(N$TEC, "N TEC")
dev.copy(pdf, "data_vars_3_N_TEC_qqplot.pdf")
dev.off()
getQQ(N$dTEC, "N dTEC")
dev.copy(pdf, "data_vars_3_N_dTEC_qqplot.pdf")
dev.off()
getQQ(N$Bx, "N Bx")
dev.copy(pdf, "data_vars_3_N_Bx_qqplot.pdf")
dev.off()
getQQ(N$By, "N By")
dev.copy(pdf, "data_vars_3_N_By_qqplot.pdf")
dev.off()
getQQ(N$Bz, "N Bz")
dev.copy(pdf, "data_vars_3_N_Bz_qqplot.pdf")
dev.off()
getQQ(N$Dst, "N Dst")
dev.copy(pdf, "data_vars_3_N_Dst_qqplot.pdf")
dev.off()
getQQ(N$ap, "N ap")
dev.copy(pdf, "data_vars_3_N_ap_qqplot.pdf")
dev.off()
#print(shapiro.test(N$TEC))
#print(shapiro.test(N$dTEC))
#print(shapiro.test(N$Bx))
#print(shapiro.test(N$By))
#print(shapiro.test(N$Bz))
#print(shapiro.test(N$Dst))
#print(shapiro.test(N$ap))
print(ks.test(N$TEC, "pnorm"))
print(ks.test(N$dTEC, "pnorm"))
print(ks.test(N$Bx, "pnorm"))
print(ks.test(N$By, "pnorm"))
print(ks.test(N$Bz, "pnorm"))
print(ks.test(N$Dst, "pnorm"))
print(ks.test(N$ap, "pnorm"))
sink()

sink("data_vars_3_R_test_normal.txt")
print(length(R$TEC))
getQQ(R$TEC, "R TEC")
dev.copy(pdf, "data_vars_3_R_TEC_qqplot.pdf")
dev.off()
getQQ(R$dTEC, "R dTEC")
dev.copy(pdf, "data_vars_3_R_dTEC_qqplot.pdf")
dev.off()
getQQ(R$Bx, "R Bx")
dev.copy(pdf, "data_vars_3_R_Bx_qqplot.pdf")
dev.off()
getQQ(R$By, "R By")
dev.copy(pdf, "data_vars_3_R_By_qqplot.pdf")
dev.off()
getQQ(R$Bz, "R Bz")
dev.copy(pdf, "data_vars_3_R_Bz_qqplot.pdf")
dev.off()
getQQ(R$Dst, "R Dst")
dev.copy(pdf, "data_vars_3_R_Dst_qqplot.pdf")
dev.off()
getQQ(R$ap, "R ap")
dev.copy(pdf, "data_vars_3_R_ap_qqplot.pdf")
dev.off()
print(shapiro.test(R$TEC))
print(shapiro.test(R$dTEC))
print(shapiro.test(R$Bx))
print(shapiro.test(R$By))
print(shapiro.test(R$Bz))
print(shapiro.test(R$Dst))
print(shapiro.test(R$ap))
print(ks.test(R$TEC, "pnorm"))
print(ks.test(R$dTEC, "pnorm"))
print(ks.test(R$Bx, "pnorm"))
print(ks.test(R$By, "pnorm"))
print(ks.test(R$Bz, "pnorm"))
print(ks.test(R$Dst, "pnorm"))
print(ks.test(R$ap, "pnorm"))
sink()

sink("data_vars_3_T_test_normal.txt")
print(length(T$TEC))
getQQ(T$TEC, "T TEC")
dev.copy(pdf, "data_vars_3_T_TEC_qqplot.pdf")
dev.off()
getQQ(T$dTEC, "T dTEC")
dev.copy(pdf, "data_vars_3_T_dTEC_qqplot.pdf")
dev.off()
getQQ(T$Bx, "T Bx")
dev.copy(pdf, "data_vars_3_T_Bx_qqplot.pdf")
dev.off()
getQQ(T$By, "T By")
dev.copy(pdf, "data_vars_3_T_By_qqplot.pdf")
dev.off()
getQQ(T$Bz, "T Bz")
dev.copy(pdf, "data_vars_3_T_Bz_qqplot.pdf")
dev.off()
getQQ(T$Dst, "T Dst")
dev.copy(pdf, "data_vars_3_T_Dst_qqplot.pdf")
dev.off()
getQQ(T$ap, "T ap")
dev.copy(pdf, "data_vars_3_T_ap_qqplot.pdf")
dev.off()
print(shapiro.test(T$TEC))
print(shapiro.test(T$dTEC))
print(shapiro.test(T$Bx))
print(shapiro.test(T$By))
print(shapiro.test(T$Bz))
print(shapiro.test(T$Dst))
print(shapiro.test(T$ap))
print(ks.test(T$TEC, "pnorm"))
print(ks.test(T$dTEC, "pnorm"))
print(ks.test(T$Bx, "pnorm"))
print(ks.test(T$By, "pnorm"))
print(ks.test(T$Bz, "pnorm"))
print(ks.test(T$Dst, "pnorm"))
print(ks.test(T$ap, "pnorm"))
sink()

sink("data_vars_3_E_test_normal.txt")
print(length(E$TEC))
getQQ(E$TEC, "E TEC")
dev.copy(pdf, "data_vars_3_E_TEC_qqplot.pdf")
dev.off()
getQQ(E$dTEC, "E dTEC")
dev.copy(pdf, "data_vars_3_E_dTEC_qqplot.pdf")
dev.off()
getQQ(E$Bx, "E Bx")
dev.copy(pdf, "data_vars_3_E_Bx_qqplot.pdf")
dev.off()
getQQ(E$By, "E By")
dev.copy(pdf, "data_vars_3_E_By_qqplot.pdf")
dev.off()
getQQ(E$Bz, "E Bz")
dev.copy(pdf, "data_vars_3_E_Bz_qqplot.pdf")
dev.off()
getQQ(E$Dst, "E Dst")
dev.copy(pdf, "data_vars_3_E_Dst_qqplot.pdf")
dev.off()
getQQ(E$ap, "E ap")
dev.copy(pdf, "data_vars_3_E_ap_qqplot.pdf")
dev.off()
print(shapiro.test(E$TEC))
print(shapiro.test(E$dTEC))
print(shapiro.test(E$Bx))
print(shapiro.test(E$By))
print(shapiro.test(E$Bz))
print(shapiro.test(E$Dst))
print(shapiro.test(E$ap))
print(ks.test(E$TEC, "pnorm"))
print(ks.test(E$dTEC, "pnorm"))
print(ks.test(E$Bx, "pnorm"))
print(ks.test(E$By, "pnorm"))
print(ks.test(E$Bz, "pnorm"))
print(ks.test(E$Dst, "pnorm"))
print(ks.test(E$ap, "pnorm"))
sink()